### ISSUE TITLE
strategies for contextual styling

### ISSUE THREAD

**Issue by itajaja** [Khan/aphrodite#108]
Hello! I'd like to know which strategies do you adopt for contextual style. Let's say I have a Button component that should be displayed differently depending if it's in a Modal or in a Panel component:

```html
<Modal>
    <Button>Click me!</Button>
<Modal>
<Panel>
    <Button>Click me!</Button>
</Panel>
```

the two buttons share the same style, except the background and the font color.

With css variables I would do something like

```css
.modal { --widgetBg: black; --widgetTextColor: white; }
.panel { --widgetBg: black; --widgetTextColor: white; }
.button { background: var(--widgetBg); color: var(--widgetTextColor) }
```

What's a good strategy for adding "contextual" style with aphrodite? Sure, I can do something like:

```html
<Modal>
    <Button bStyle="regular">Click me!</Button>
<Modal>
<Panel>
    <Button bStyle="inverted">Click me!</Button>
</Panel>
```

but I feel it's not the Modal or Panel's user responsibility to set that. I could make a context with the variables, so that all the components can access that and than chose an appropriate style, but it's still not as flexible as the css variables approach. 

I know aphrodite's goal is to avoid "nested" behaviors, but sometimes that's exactly what you need.

Thanks for the work, I ❤️  aphrodite so far!

**Comment by itajaja** [comment]
moreOver, `StyleSheet.create` camelizes the variables, so that 

```js
StyleSheet.create({
  body: {
    '--myVar': 'red',
  }
})
```

outputs something like

```css
.body: {
   --my-var: red
}
```

I don't think that's a desirable effect (should I open a separate issue for this?)
