### ISSUE TITLE
Adjacent sibling selector?

### ISSUE THREAD

**Issue by aaronjensen** [Khan/aphrodite#133]
I often do things like:

```css
.box + .box {
  margin-left: 1rem
}
```

Is this possible w/ aphrodite?
