### ISSUE TITLE
Will aphrodite support substates in styles?

### ISSUE THREAD

**Issue by jettangs** [Khan/aphrodite#177]
Example:
```css
const styles= StyleSheet.create({
link: {
      color: 'blue',
}
seletedLink: {
      color: 'red',
}
})
```
or I could write like this:
```
const link= StyleSheet.create({
default: {
      color: 'blue',
}
seleted: {
      color: 'red',
}
})
```
The first writing looks fussy, but I don't want to combind  a series of styles, because styles so many,
maybe, need a `extend` syntax like css module `@composes` ?
PS: I am writing a plugin `aphrodite-breakpoint` to support standalone breakpoint definition for aphrodite, maybe need some idea to prefect it.
