### ISSUE TITLE
Order of properties can change in different environments

### ISSUE THREAD

**Issue by lencioni** [Khan/aphrodite#199]
I am noticing a difference in how the style properties are ordered between a development environment and a production environment. Essentially, I have a couple of styles that look like this:

```js
foo: {
  margin: 0,
},

bar: {
  marginRight: 16,
},
```

I am applying them to my element like this `css(foo, isBar && bar)`.

In my development environment (a story in react storybook), the component is styled as expected, with 0 margin all around except for the 16px of margin on the right. However, in production, my 16px right margin is missing. Looking at the generated styles, I can see that all of my properties are there, but the order is different.

In storybook:

```css
.an_aphrodite_selector {
  margin: 0 !important;
  margin-right: 16px !important;
}
```

In production:

```css
.an_aphrodite_selector {
  margin-right: 16px !important;
  margin: 0 !important;
}
```

I also have some more styles than just margin, but I am just mentioning these because it highlights the specific problem. Here's the specific CSS that is generated in development (whitespace added for readability):

```css
.text_1aunhvg-o_O-tab_8ndy7u-o_O-tab_micro_17dr3ug-o_O-text_muted_td6kew-o_O-text_spacedTabs_1fn1i59-o_O-tab_selected_6lr1xw{
	-webkit-transition-timing-function:ease-out !important;
	-webkit-transition-property:color !important;
	-webkit-transition-duration:300ms !important;
	letter-spacing:0.4px !important;
	padding-top:12px !important;
	padding-bottom:12px !important;
	color:#008489 !important;
	margin:0px !important;
	background-color:transparent !important;
	border-width:0px !important;
	border-bottom:2px solid #008489 !important;
	font-size:12px !important;
	cursor:pointer !important;
	margin-right:16px !important;
	padding-left:0px !important;
	padding-right:0px !important;
	font-weight:700 !important;
	transition-property:color !important;
	transition-duration:300ms !important;
	transition-timing-function:ease-out !important;
	font-family:Circular,-apple-system,BlinkMacSystemFont,Roboto,Helvetica Neue,sans-serif !important;
	line-height:16px !important;
	bottom:-1px !important;
}
```

and in production:

```css
.text_1aunhvg-o_O-tab_8ndy7u-o_O-tab_micro_ltghyi-o_O-text_muted_td6kew-o_O-text_spacedTabs_1fn1i59-o_O-tab_selected_6lr1xw{
	padding-left:0px !important;
	bottom:-1px !important;
	font-weight:700 !important;
	border-width:0px !important;
	border-bottom:2px solid #008489 !important;
	cursor:pointer !important;
	padding-top:12px !important;
	font-size:12px !important;
	letter-spacing:0.4px !important;
	font-family:Circular,-apple-system,BlinkMacSystemFont,Roboto,Helvetica Neue,sans-serif !important;
	margin-right:16px !important;
	padding-right:0px !important;
	padding-bottom:18px !important;
	line-height:16px !important;
	color:#008489 !important;
	margin:0px !important;
	background-color:transparent !important;
	transition-property:color !important;
	transition-duration:300ms !important;
	transition-timing-function:ease-out !important;
	-webkit-transition-property:color !important;
	-webkit-transition-duration:300ms !important;
	-webkit-transition-timing-function:ease-out !important;
}
```

Any ideas what might be happening here or where to look? It seems that there might be some code that expects the order of things to be stable when that is not the case. Or perhaps we are transforming (Babel) or polyfilling something slightly differently in these two environments? 

Aphrodite v0.5.0
