### ISSUE TITLE
Feature request: Conversion helper CSS -> Aphrodite

### ISSUE THREAD

**Issue by Soreine** [Khan/aphrodite#230]
I was wondering if anyone had made a tool to "convert" style rules from a CSS syntax to a JS object syntax, as accepted by Aphrodite.

This does not need to be fancy, nor smart. Just a small helper to help importing existing CSS rules into Aphrodite. The rules would still need to be refactored manually of course, but at least, the directives would be camel cased as needed, and semi-colons would be converted to colons etc.

Example:

```css
.my-class {
    transform: translateX(-90%);
    padding-bottom: 3;
}
```

```js
{
    myClass: {
        transform: 'translateX(-90%)',
        paddingBottom: '3'
    }
}
