### ISSUE TITLE
Setting multiple values for the same attribute

### ISSUE THREAD

**Issue by tp** [Khan/aphrodite#28]
Since I did not find any documentation, I just wanted to ask whether it it possible to set multiple values for the same attribute.

Like for example when you would want to use multiple values with vendor prefixes:

```css
.myClass {
    cursor:-moz-grab;
    cursor:-webkit-grab;
    cursor:grab;
}
```
