### ISSUE TITLE
how to write Nesting ?

### ISSUE THREAD

**Issue by zhishaofei3** [Khan/aphrodite#319]
````css
.jump-btn {
            width: 32px;
            height: 32px;
            background: url('jump_btn.png') no-repeat 0 0;
            &.disabled {
                background-position: -32px 0;
            }
            &.back {
                background-position: -64px 0;
            }
}
````

**Comment by dmiller9911** [comment]
This is somewhat not supported. The only real nesting that is supported is pseudo selectors (:hover, :active, etc) and media queries. The way you would do it in Aphrodite would be to do something like
```jsx
const styles = StyleSheet.create({
  jumpBtn: {
    width: 32,
    height: 32,
    background: 'background: url('jump_btn.png') no-repeat 0 0',
  },
  disabled: {
    backgroundPosition: '-32px 0',
  },
  back: {
    backgroundPosition: '-64px 0',
  },
});
const classes = css(styles.jumpBtn, isDisabled && styles.disabled, isBack && styles.back);
```
There is an escape hatch by doing something like
```jsx
const styles = StyleSheet.create({
  jumpBtn: {
    ...styles,
    ':not(foobar).disabled': { ....disabledStyles }
  },
});
const classes = 'disabled' + css(styles.jumpBtn)
```
I would try hard to not use this though.

**Comment by zhishaofei3** [comment]
thank you verymuch @dmiller9911

**Comment by nakwa** [comment]
You can do that pretty easily with the extension.

```
import { StyleSheet as Aphrodite } from 'aphrodite';
const { StyleSheet, css } = Aphrodite.extend([{
  selectorHandler: (selector, baseSelector, generateSubtreeStyles) => {
    if (selector[0] === '>') {
      const tag = selector.slice(1);
      const nestedTag = generateSubtreeStyles(`${baseSelector} ${tag}`);
      return nestedTag;
    }
    return null;
  }
}]);
```

Then just write your style as :
```
{
    color: "red",
    "> p": {
      textTransform: 'uppercase',
      fontSize: '0.8em',
      textDecoration: 'none'
    }
  }
``` 

Even better, just wrap all your style into a function like this : 

```
function mapNestedStyle(stylesheet) {
  _.each(stylesheet, (item, selectorKey) => {
    const selectors = item._definition;
    _.each(selectors, (selector, key) => {
      if (_.isPlainObject(selector) && key[0] !== '>' && key[0] !== ':' && key[0] !== '@') {
        delete selectors[key];
        selectors[`> ${key}`] = selector;
      }
    });
  });
  return stylesheet;
}
```
So that you can just write : 

```
{
    color: "red",
    p: {
      textTransform: 'uppercase',
      fontSize: '0.8em',
      textDecoration: 'none'
    }
  }
``` 

I hope this will become part of the core functionalities at some point :) .

**Comment by Sibz** [comment]
@nakwa Perfect!

I do think selectors for ' ' (space - all descendants) and >(direct child descendants) should be included - it seems wrong to have to add styles to every component that needs styling.
For example, every label in a form... I want to just put the styles on the form to apply to all the labels.

I modified as follows

```javascript
const { StyleSheet, css } = Aphrodite.extend([{
  selectorHandler: (selector, baseSelector, generateSubtreeStyles) => {
    if (selector[0] === ' ') {
      const tag = selector.slice(1);
      const nestedTag = generateSubtreeStyles(`${baseSelector} ${tag}`);
      return nestedTag;
    } else if (selector[0] === '>') {
      const tag = selector.slice(1);
      const nestedTag = generateSubtreeStyles(`${baseSelector} > ${tag}`);
      return nestedTag;
    }
    return null;
  }
}]);
```

so now this works:
```javascript
form: {
      borderWidth: 1,
      borderStyle: "solid",
      borderColor: "black",
      margin: 5,
      padding: 5,
      borderRadius: 7,
      " label" :{
        backgroundColor: "pink",
      }
    }
```
and produces:
```css
.Form_1pi38cr {
    border-width: 1px !important;
    border-style: solid !important;
    border-color: rgb(66, 139, 202) !important;
    margin: 5px !important;
    padding: 5px !important;
    border-radius: 7px !important;
}
.Form_1pi38cr label {
    background-color: rgb(91, 192, 222) !important;
}
```

Would be great for it to be core functionality. Might look at the code base.
I use typescript so had to modify the typings file slightly for linting to pass.
