### ISSUE TITLE
content looses "" around the content

### ISSUE THREAD

**Issue by tp** [Khan/aphrodite#32]
```jsx
<div className={css(styles.div)}></div>
```

```js
style.div = {
  ':before': {
    content: "test",
  }
};
```

generates

```css
.div_1pd8e9z:before{content:test !important;}
```

which just leaves the div empty (notice the missing "" around the content string).

A convoluted workaround exists though:

```js
style.div = {
  ':before': {
    content: `"test"`,
  }
};
```

which generates the following CSS:
```css
.div_10tj0xl:before{content:"test" !important;}
```
